FROM alpine-sdk

RUN apk add --no-cache libxcb-static libxcb-dev \
    xcb-imdkit-dev \
    xcb-util-cursor-dev \
    xcb-util-dev \
    xcb-util-errors-dev \
    xcb-util-image-dev \
    xcb-util-keysyms-dev \
    xcb-util-renderutil-dev \
    xcb-util-wm-dev \
    xcb-util-xrm-dev \
    libx11-dev \
    libx11-static \
    libxkbcommon-dev \
    libxkbcommon-static \
    libxkbcommon-x11


# docker build -t alpine-x11 .
